mod config;
mod conversion;
mod misc;
mod overlay;
pub mod tray;

// Re-export config types for updater.rs
pub use config::{AppConfig, read_config_file, write_config_file};

// Re-export all commands. The `__cmd__xxx` companions are the wrappers
// generated by the `#[tauri::command]` macro and need to be re-exported
// publicly so that `tauri::generate_handler!` in `lib.rs` can find them.
pub use config::{get_config, update_config, clear_config, __cmd__get_config, __cmd__update_config, __cmd__clear_config};
pub use conversion::{test_command, convert_zip, convert_resource_pack, convert_resource_packs_batch};
pub use misc::{get_logs, set_dev_mode, get_dev_mode, log_notification, export_logs, get_log_path, open_folder, write_file, create_dir};
pub use overlay::{get_overlay_projects, delete_overlay_project, overlay_init, import_lang_from_parent, get_overlay_lang, save_overlay_lang, read_lang_file, get_overlay_json, save_overlay_json, export_overlay_share_code, import_overlay_share_code, overlay_package, get_overlay_settings, save_overlay_settings, overlay_set_parent_pack};
