//! 由脚本从旧实现抽取的重命名对（`rename_blocks.rs` 与 `process_blocks.rs`）。
//!
//! 抽取而不是手抄：约 200 条数据，手抄必错。顺序固定（旧实现是 HashMap，顺序不确定）。

/// 从旧实现脚本抽取的重命名表（顺序固定；旧实现用 HashMap，顺序本就不确定）。
pub const ITEM_PAIRS: [(&str, &str); 110] = [
    ("gold_sword.png", "golden_sword.png"), ("wood_sword.png", "wooden_sword.png"),
    ("gold_helmet.png", "golden_helmet.png"), ("gold_chestplate.png", "golden_chestplate.png"),
    ("gold_leggings.png", "golden_leggings.png"), ("gold_boots.png", "golden_boots.png"),
    ("apple_golden.png", "golden_apple.png"), ("bow_standby.png", "bow.png"),
    ("book_enchanted.png", "enchanted_book.png"), ("wood_axe.png", "wooden_axe.png"),
    ("wood_pickaxe.png", "wooden_pickaxe.png"), ("wood_shovel.png", "wooden_shovel.png"),
    ("wood_hoe.png", "wooden_hoe.png"), ("gold_axe.png", "golden_axe.png"),
    ("gold_pickaxe.png", "golden_pickaxe.png"), ("gold_shovel.png", "golden_shovel.png"),
    ("gold_hoe.png", "golden_hoe.png"), ("fishing_rod_uncast.png", "fishing_rod.png"),
    ("potion_bottle_empty.png", "glass_bottle.png"),
    ("potion_bottle_drinkable.png", "potion.png"),
    ("potion_bottle_splash.png", "splash_potion.png"),
    ("potion_bottle_lingering.png", "lingering_potion.png"),
    ("spider_eye_fermented.png", "fermented_spider_eye.png"),
    ("melon_speckled.png", "glistering_melon_slice.png"), ("melon.png", "melon_slice.png"),
    ("carrot_golden.png", "golden_carrot.png"), ("porkchop_raw.png", "porkchop.png"),
    ("porkchop_cooked.png", "cooked_porkchop.png"), ("chicken_raw.png", "chicken.png"),
    ("chicken_cooked.png", "cooked_chicken.png"), ("rabbit_raw.png", "rabbit.png"),
    ("rabbit_cooked.png", "cooked_rabbit.png"), ("beef_raw.png", "beef.png"),
    ("beef_cooked.png", "cooked_beef.png"), ("boat.png", "oak_boat.png"),
    ("book_normal.png", "book.png"), ("book_writable.png", "writable_book.png"),
    ("book_written.png", "written_book.png"), ("bucket_empty.png", "bucket.png"),
    ("bucket_lava.png", "lava_bucket.png"), ("bucket_water.png", "water_bucket.png"),
    ("bucket_milk.png", "milk_bucket.png"), ("door_acacia.png", "acacia_door.png"),
    ("door_birch.png", "birch_door.png"), ("door_dark_oak.png", "dark_oak_door.png"),
    ("door_iron.png", "iron_door.png"), ("door_jungle.png", "jungle_door.png"),
    ("door_spruce.png", "spruce_door.png"), ("door_wood.png", "oak_door.png"),
    ("dye_powder_black.png", "ink_sac.png"), ("dye_powder_blue.png", "lapis_lazuli.png"),
    ("dye_powder_brown.png", "cocoa_beans.png"), ("dye_powder_cyan.png", "cyan_dye.png"),
    ("dye_powder_gray.png", "gray_dye.png"), ("dye_powder_green.png", "green_dye.png"),
    ("dye_powder_light_blue.png", "light_blue_dye.png"),
    ("dye_powder_lime.png", "lime_dye.png"), ("dye_powder_magenta.png", "magenta_dye.png"),
    ("dye_powder_orange.png", "orange_dye.png"), ("dye_powder_pink.png", "pink_dye.png"),
    ("dye_powder_purple.png", "purple_dye.png"), ("dye_powder_red.png", "red_dye.png"),
    ("dye_powder_silver.png", "light_gray_dye.png"), ("dye_powder_white.png", "bone_meal.png"),
    ("dye_powder_yellow.png", "yellow_dye.png"), ("fireball.png", "fire_charge.png"),
    ("fireworks.png", "firework_rocket.png"), ("fireworks_charge.png", "firework_star.png"),
    ("firework_charge_overlay.png", "firework_star_overlay.png"),
    ("fish_cod_raw.png", "cod.png"), ("fish_cod_cooked.png", "cooked_cod.png"),
    ("fish_salmon_raw.png", "salmon.png"), ("fish_salmon_cooked.png", "cooked_salmon.png"),
    ("fish_clownfish_raw.png", "tropical_fish.png"),
    ("fish_pufferfish_raw.png", "pufferfish.png"), ("map_empty.png", "map.png"),
    ("map_filled.png", "filled_map.png"), ("minecart_chest.png", "chest_minecart.png"),
    ("minecart_command_block.png", "command_block_minecart.png"),
    ("minecart_furnace.png", "furnace_minecart.png"),
    ("minecart_hopper.png", "hopper_minecart.png"), ("minecart_normal.png", "minecart.png"),
    ("minecart_tnt.png", "tnt_minecart.png"), ("mutton_cooked.png", "cooked_mutton.png"),
    ("mutton_raw.png", "mutton.png"), ("netherbrick.png", "nether_brick.png"),
    ("potato_baked.png", "baked_potato.png"), ("potato_poisonous.png", "poisonous_potato.png"),
    ("record_11.png", "music_disc_11.png"), ("record_13.png", "music_disc_13.png"),
    ("record_blocks.png", "music_disc_blocks.png"), ("record_cat.png", "music_disc_cat.png"),
    ("record_chirp.png", "music_disc_chirp.png"), ("record_far.png", "music_disc_far.png"),
    ("record_mail.png", "music_disc_mail.png"),
    ("record_mellohi.png", "music_disc_mellohi.png"),
    ("record_stal.png", "music_disc_stal.png"), ("record_strad.png", "music_disc_strad.png"),
    ("record_wait.png", "music_disc_wait.png"), ("record_ward.png", "music_disc_ward.png"),
    ("record_mall.png", "music_disc_mall.png"), ("redstone_dust.png", "redstone.png"),
    ("reeds.png", "sugar_cane.png"), ("seeds_melon.png", "melon_seeds.png"),
    ("seeds_pumpkin.png", "pumpkin_seeds.png"), ("seeds_wheat.png", "wheat_seeds.png"),
    ("sign.png", "oak_sign.png"), ("slimeball.png", "slime_ball.png"),
    ("wooden_armorstand.png", "armor_stand.png"),
    ("gold_horse_armor.png", "golden_horse_armor.png"),
];

/// 从旧实现脚本抽取的重命名表（顺序固定；旧实现用 HashMap，顺序本就不确定）。
pub const BLOCK_PAIRS: [(&str, &str); 44] = [
    ("cobblestone_mossy.png", "mossy_cobblestone.png"),
    ("stone_granite_smooth.png", "polished_granite.png"),
    ("stone_diorite_smooth.png", "polished_diorite.png"),
    ("stone_andesite_smooth.png", "polished_andesite.png"),
    ("hardened_clay_stained_white.png", "white_terracotta.png"),
    ("hardened_clay_stained_orange.png", "orange_terracotta.png"),
    ("hardened_clay_stained_magenta.png", "magenta_terracotta.png"),
    ("hardened_clay_stained_light_blue.png", "light_blue_terracotta.png"),
    ("hardened_clay_stained_yellow.png", "yellow_terracotta.png"),
    ("hardened_clay_stained_lime.png", "lime_terracotta.png"),
    ("hardened_clay_stained_pink.png", "pink_terracotta.png"),
    ("hardened_clay_stained_gray.png", "gray_terracotta.png"),
    ("hardened_clay_stained_light_gray.png", "light_gray_terracotta.png"),
    ("hardened_clay_stained_cyan.png", "cyan_terracotta.png"),
    ("hardened_clay_stained_purple.png", "purple_terracotta.png"),
    ("hardened_clay_stained_blue.png", "blue_terracotta.png"),
    ("hardened_clay_stained_brown.png", "brown_terracotta.png"),
    ("hardened_clay_stained_green.png", "green_terracotta.png"),
    ("hardened_clay_stained_red.png", "red_terracotta.png"),
    ("hardened_clay_stained_black.png", "black_terracotta.png"),
    ("planks_oak.png", "oak_planks.png"), ("planks_birch.png", "birch_planks.png"),
    ("planks_spruce.png", "spruce_planks.png"), ("planks_jungle.png", "jungle_planks.png"),
    ("planks_acacia.png", "acacia_planks.png"), ("planks_dark_oak.png", "dark_oak_planks.png"),
    ("sapling_oak.png", "oak_sapling.png"), ("sapling_birch.png", "birch_sapling.png"),
    ("sapling_spruce.png", "spruce_sapling.png"), ("sapling_jungle.png", "jungle_sapling.png"),
    ("sapling_acacia.png", "acacia_sapling.png"),
    ("sapling_dark_oak.png", "dark_oak_sapling.png"), ("leaves_oak.png", "oak_leaves.png"),
    ("leaves_birch.png", "birch_leaves.png"), ("leaves_spruce.png", "spruce_leaves.png"),
    ("leaves_jungle.png", "jungle_leaves.png"), ("leaves_acacia.png", "acacia_leaves.png"),
    ("leaves_dark_oak.png", "dark_oak_leaves.png"), ("log_oak.png", "oak_log.png"),
    ("log_birch.png", "birch_log.png"), ("log_spruce.png", "spruce_log.png"),
    ("log_jungle.png", "jungle_log.png"), ("log_acacia.png", "acacia_log.png"),
    ("log_dark_oak.png", "dark_oak_log.png"),
];

/// 从旧实现脚本抽取的重命名表（顺序固定；旧实现用 HashMap，顺序本就不确定）。
pub const PROCESS_BLOCK_PAIRS: [(&str, &str); 243] = [
    ("stone_granite.png", "granite.png"), ("stone_granite_smooth.png", "polished_granite.png"),
    ("stone_diorite.png", "diorite.png"), ("stone_diorite_smooth.png", "polished_diorite.png"),
    ("stone_andesite.png", "andesite.png"),
    ("stone_andesite_smooth.png", "polished_andesite.png"),
    ("grass_side.png", "grass_block_side.png"), ("grass_top.png", "grass_block_top.png"),
    ("dirt_podzol_side.png", "podzol_side.png"), ("dirt_podzol_top.png", "podzol_top.png"),
    ("planks_acacia.png", "acacia_planks.png"), ("planks_big_oak.png", "dark_oak_planks.png"),
    ("planks_birch.png", "birch_planks.png"), ("planks_jungle.png", "jungle_planks.png"),
    ("planks_spruce.png", "spruce_planks.png"), ("planks_oak.png", "oak_planks.png"),
    ("quartz_ore.png", "nether_quartz_ore.png"), ("sponge_wet.png", "wet_sponge.png"),
    ("sandstone_normal.png", "sandstone.png"),
    ("sandstone_carved.png", "chiseled_sandstone.png"),
    ("sandstone_smooth.png", "cut_sandstone.png"),
    ("red_sandstone_normal.png", "red_sandstone.png"),
    ("red_sandstone_carved.png", "chiseled_red_sandstone.png"),
    ("red_sandstone_smooth.png", "cut_red_sandstone.png"),
    ("wool_colored_black.png", "black_wool.png"), ("wool_colored_blue.png", "blue_wool.png"),
    ("wool_colored_brown.png", "brown_wool.png"), ("wool_colored_cyan.png", "cyan_wool.png"),
    ("wool_colored_gray.png", "gray_wool.png"), ("wool_colored_green.png", "green_wool.png"),
    ("wool_colored_light_blue.png", "light_blue_wool.png"),
    ("wool_colored_lime.png", "lime_wool.png"),
    ("wool_colored_magenta.png", "magenta_wool.png"),
    ("wool_colored_orange.png", "orange_wool.png"), ("wool_colored_pink.png", "pink_wool.png"),
    ("wool_colored_purple.png", "purple_wool.png"), ("wool_colored_red.png", "red_wool.png"),
    ("wool_colored_silver.png", "light_gray_wool.png"),
    ("wool_colored_white.png", "white_wool.png"),
    ("wool_colored_yellow.png", "yellow_wool.png"),
    ("stone_slab_side.png", "smooth_stone_slab_side.png"),
    ("stone_slab_top.png", "smooth_stone.png"), ("brick.png", "bricks.png"),
    ("nether_brick.png", "nether_bricks.png"), ("stonebrick.png", "stone_bricks.png"),
    ("stonebrick_carved.png", "chiseled_stone_bricks.png"),
    ("stonebrick_mossy.png", "mossy_stone_bricks.png"),
    ("quartz_block_chiseled.png", "chiseled_quartz_block.png"),
    ("quartz_block_lines.png", "quartz_pillar.png"),
    ("quartz_block_lines_top.png", "quartz_pillar_top.png"),
    ("prismarine_dark.png", "dark_prismarine.png"), ("prismarine_rough.png", "prismarine.png"),
    ("prismarine_rough.png.mcmeta", "prismarine.png.mcmeta"), ("anvil_base.png", "anvil.png"),
    ("anvil_top_damaged_0.png", "anvil_top.png"),
    ("anvil_top_damaged_1.png", "chipped_anvil_top.png"),
    ("anvil_top_damaged_2.png", "damaged_anvil_top.png"),
    ("carrots_stage_0.png", "carrots_stage0.png"),
    ("carrots_stage_1.png", "carrots_stage1.png"),
    ("carrots_stage_2.png", "carrots_stage2.png"),
    ("carrots_stage_3.png", "carrots_stage3.png"),
    ("cobblestone_mossy.png", "mossy_cobblestone.png"),
    ("cocoa_stage_0.png", "cocoa_stage0.png"), ("cocoa_stage_1.png", "cocoa_stage1.png"),
    ("cocoa_stage_2.png", "cocoa_stage2.png"), ("comparator_off.png", "comparator.png"),
    ("deadbush.png", "dead_bush.png"),
    ("dispenser_front_horizontal.png", "dispenser_horizontal.png"),
    ("door_acacia_lower.png", "acacia_door_bottom.png"),
    ("door_acacia_upper.png", "acacia_door_top.png"),
    ("door_birch_lower.png", "birch_door_bottom.png"),
    ("door_birch_upper.png", "birch_door_top.png"),
    ("door_dark_oak_lower.png", "dark_oak_door_bottom.png"),
    ("door_dark_oak_upper.png", "dark_oak_door_top.png"),
    ("door_iron_lower.png", "iron_door_bottom.png"),
    ("door_iron_upper.png", "iron_door_top.png"),
    ("door_jungle_lower.png", "jungle_door_bottom.png"),
    ("door_jungle_upper.png", "jungle_door_top.png"),
    ("door_spruce_lower.png", "spruce_door_bottom.png"),
    ("door_spruce_upper.png", "spruce_door_top.png"),
    ("door_wood_lower.png", "oak_door_bottom.png"),
    ("door_wood_upper.png", "oak_door_top.png"),
    ("double_plant_fern_bottom.png", "large_fern_bottom.png"),
    ("double_plant_fern_top.png", "large_fern_top.png"),
    ("double_plant_grass_bottom.png", "tall_grass_bottom.png"),
    ("double_plant_grass_top.png", "tall_grass_top.png"),
    ("double_plant_paeonia_bottom.png", "peony_bottom.png"),
    ("double_plant_paeonia_top.png", "peony_top.png"),
    ("double_plant_rose_bottom.png", "rose_bush_bottom.png"),
    ("double_plant_rose_top.png", "rose_bush_top.png"),
    ("double_plant_sunflower_back.png", "sunflower_back.png"),
    ("double_plant_sunflower_bottom.png", "sunflower_bottom.png"),
    ("double_plant_sunflower_top.png", "sunflower_top.png"),
    ("double_plant_sunflower_front.png", "sunflower_front.png"),
    ("double_plant_syringa_bottom.png", "lilac_bottom.png"),
    ("double_plant_syringa_top.png", "lilac_top.png"),
    ("dropper_front_horizontal.png", "dropper_front.png"),
    ("endframe_eye.png", "end_portal_frame_eye.png"),
    ("endframe_side.png", "end_portal_frame_side.png"),
    ("endframe_top.png", "end_portal_frame_top.png"), ("farmland_dry.png", "farmland.png"),
    ("farmland_wet.png", "farmland_moist.png"), ("fire_layer_0.png", "fire_0.png"),
    ("fire_layer_1.png", "fire_1.png"), ("flower_allium.png", "allium.png"),
    ("flower_blue_orchid.png", "blue_orchid.png"), ("flower_dandelion.png", "dandelion.png"),
    ("flower_houstonia.png", "azure_bluet.png"), ("flower_oxeye_daisy.png", "oxeye_daisy.png"),
    ("flower_rose.png", "poppy.png"), ("flower_tulip_orange.png", "orange_tulip.png"),
    ("flower_tulip_pink.png", "pink_tulip.png"), ("flower_tulip_red.png", "red_tulip.png"),
    ("flower_tulip_white.png", "white_tulip.png"),
    ("furnace_front_off.png", "furnace_front.png"),
    ("glass_black.png", "black_stained_glass.png"),
    ("glass_blue.png", "blue_stained_glass.png"),
    ("glass_brown.png", "brown_stained_glass.png"),
    ("glass_cyan.png", "cyan_stained_glass.png"), ("glass_gray.png", "gray_stained_glass.png"),
    ("glass_green.png", "green_stained_glass.png"),
    ("glass_light_blue.png", "light_blue_stained_glass.png"),
    ("glass_lime.png", "lime_stained_glass.png"),
    ("glass_magenta.png", "magenta_stained_glass.png"),
    ("glass_orange.png", "orange_stained_glass.png"),
    ("glass_pink.png", "pink_stained_glass.png"),
    ("glass_purple.png", "purple_stained_glass.png"),
    ("glass_red.png", "red_stained_glass.png"),
    ("glass_silver.png", "light_gray_stained_glass.png"),
    ("glass_white.png", "white_stained_glass.png"),
    ("glass_yellow.png", "yellow_stained_glass.png"),
    ("glass_pane_top_black.png", "black_stained_glass_pane_top.png"),
    ("glass_pane_top_blue.png", "blue_stained_glass_pane_top.png"),
    ("glass_pane_top_brown.png", "brown_stained_glass_pane_top.png"),
    ("glass_pane_top_cyan.png", "cyan_stained_glass_pane_top.png"),
    ("glass_pane_top_gray.png", "gray_stained_glass_pane_top.png"),
    ("glass_pane_top_green.png", "green_stained_glass_pane_top.png"),
    ("glass_pane_top_light_blue.png", "light_blue_stained_glass_pane_top.png"),
    ("glass_pane_top_lime.png", "lime_stained_glass_pane_top.png"),
    ("glass_pane_top_magenta.png", "magenta_stained_glass_pane_top.png"),
    ("glass_pane_top_orange.png", "orange_stained_glass_pane_top.png"),
    ("glass_pane_top_pink.png", "pink_stained_glass_pane_top.png"),
    ("glass_pane_top_purple.png", "purple_stained_glass_pane_top.png"),
    ("glass_pane_top_red.png", "red_stained_glass_pane_top.png"),
    ("glass_pane_top_silver.png", "light_gray_stained_glass_pane_top.png"),
    ("glass_pane_top_white.png", "white_stained_glass_pane_top.png"),
    ("glass_pane_top_yellow.png", "yellow_stained_glass_pane_top.png"),
    ("grass_side_overlay.png", "grass_block_side_overlay.png"),
    ("grass_side_snowed.png", "grass_block_snow.png"), ("hardened_clay.png", "terracotta.png"),
    ("hardened_clay_stained_black.png", "black_terracotta.png"),
    ("hardened_clay_stained_blue.png", "blue_terracotta.png"),
    ("hardened_clay_stained_brown.png", "brown_terracotta.png"),
    ("hardened_clay_stained_cyan.png", "cyan_terracotta.png"),
    ("hardened_clay_stained_gray.png", "gray_terracotta.png"),
    ("hardened_clay_stained_green.png", "green_terracotta.png"),
    ("hardened_clay_stained_light_blue.png", "light_blue_terracotta.png"),
    ("hardened_clay_stained_lime.png", "lime_terracotta.png"),
    ("hardened_clay_stained_magenta.png", "magenta_terracotta.png"),
    ("hardened_clay_stained_orange.png", "orange_terracotta.png"),
    ("hardened_clay_stained_pink.png", "pink_terracotta.png"),
    ("hardened_clay_stained_purple.png", "purple_terracotta.png"),
    ("hardened_clay_stained_red.png", "red_terracotta.png"),
    ("hardened_clay_stained_silver.png", "light_gray_terracotta.png"),
    ("hardened_clay_stained_white.png", "white_terracotta.png"),
    ("hardened_clay_stained_yellow.png", "yellow_terracotta.png"),
    ("ice_packed.png", "packed_ice.png"), ("itemframe_background.png", "item_frame.png"),
    ("leaves_acacia.png", "acacia_leaves.png"), ("leaves_big_oak.png", "dark_oak_leaves.png"),
    ("leaves_birch.png", "birch_leaves.png"), ("leaves_jungle.png", "jungle_leaves.png"),
    ("leaves_oak.png", "oak_leaves.png"), ("leaves_spruce.png", "spruce_leaves.png"),
    ("log_acacia.png", "acacia_log.png"), ("log_acacia_top.png", "acacia_log_top.png"),
    ("log_big_oak.png", "dark_oak_log.png"), ("log_big_oak_top.png", "dark_oak_log_top.png"),
    ("log_spruce.png", "spruce_log.png"), ("log_spruce_top.png", "spruce_log_top.png"),
    ("log_birch.png", "birch_log.png"), ("log_birch_top.png", "birch_log_top.png"),
    ("log_jungle.png", "jungle_log.png"), ("log_jungle_top.png", "jungle_log_top.png"),
    ("log_oak.png", "oak_log.png"), ("log_oak_top.png", "oak_log_top.png"),
    ("melon_stem_connected.png", "attached_melon_stem.png"),
    ("melon_stem_disconnected.png", "melon_stem.png"), ("mob_spawner.png", "spawner.png"),
    ("mushroom_block_skin_brown.png", "brown_mushroom_block.png"),
    ("mushroom_block_skin_red.png", "red_mushroom_block.png"),
    ("mushroom_block_skin_stem.png", "mushroom_stem.png"),
    ("mushroom_brown.png", "brown_mushroom.png"), ("mushroom_red.png", "red_mushroom.png"),
    ("nether_wart_stage_0.png", "nether_wart_stage0.png"),
    ("nether_wart_stage_1.png", "nether_wart_stage1.png"),
    ("nether_wart_stage_2.png", "nether_wart_stage2.png"), ("noteblock.png", "note_block.png"),
    ("piston_top_normal.png", "piston_top.png"), ("portal.png", "nether_portal.png"),
    ("potatoes_stage_0.png", "potatoes_stage0.png"),
    ("potatoes_stage_1.png", "potatoes_stage1.png"),
    ("potatoes_stage_2.png", "potatoes_stage2.png"),
    ("potatoes_stage_3.png", "potatoes_stage3.png"),
    ("pumpkin_face_off.png", "carved_pumpkin.png"),
    ("pumpkin_face_on.png", "jack_o_lantern.png"),
    ("pumpkin_stem_connected.png", "attached_pumpkin_stem.png"),
    ("pumpkin_stem_disconnected.png", "pumpkin_stem.png"),
    ("rail_activator.png", "activator_rail.png"),
    ("rail_activator_powered.png", "activator_rail_on.png"),
    ("rail_detector.png", "detector_rail.png"),
    ("rail_detector_powered.png", "detector_rail_on.png"),
    ("rail_golden.png", "powered_rail.png"),
    ("rail_golden_powered.png", "powered_rail_on.png"), ("rail_normal.png", "rail.png"),
    ("rail_normal_turned.png", "rail_corner.png"),
    ("redstone_dust_cross_overlay.png", "redstone_dust_overlay.png"),
    ("redstone_lamp_off.png", "redstone_lamp.png"),
    ("redstone_torch_on.png", "redstone_torch.png"), ("reeds.png", "sugar_cane.png"),
    ("repeater_off.png", "repeater.png"), ("sapling_acacia.png", "acacia_sapling.png"),
    ("sapling_birch.png", "birch_sapling.png"), ("sapling_jungle.png", "jungle_sapling.png"),
    ("sapling_oak.png", "oak_sapling.png"), ("sapling_roofed_oak.png", "dark_oak_sapling.png"),
    ("sapling_spruce.png", "spruce_sapling.png"),
    ("stonebrick_cracked.png", "cracked_stone_bricks.png"), ("slime.png", "slime_block.png"),
    ("tallgrass.png", "grass.png"), ("torch_on.png", "torch.png"),
    ("trapdoor.png", "oak_trapdoor.png"), ("trip_wire_source.png", "tripwire_hook.png"),
    ("waterlily.png", "lily_pad.png"), ("web.png", "cobweb.png"),
    ("wheat_stage_0.png", "wheat_stage0.png"), ("wheat_stage_1.png", "wheat_stage1.png"),
    ("wheat_stage_2.png", "wheat_stage2.png"), ("wheat_stage_3.png", "wheat_stage3.png"),
    ("wheat_stage_4.png", "wheat_stage4.png"), ("wheat_stage_5.png", "wheat_stage5.png"),
    ("wheat_stage_6.png", "wheat_stage6.png"), ("wheat_stage_7.png", "wheat_stage7.png"),
];
